// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ686oYbypjumZZHo5vL4Iqp4WxAaBO90',
    appId: '1:157073038498:web:9c46875903bcc579eacbfb',
    messagingSenderId: '157073038498',
    projectId: 'yugioh-card-manager-d3164',
    authDomain: 'yugioh-card-manager-d3164.firebaseapp.com',
    storageBucket: 'yugioh-card-manager-d3164.firebasestorage.app',
    measurementId: 'G-CE2S4M7GZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM9qnHQ80YPPQ7shO21E2_cjYM2RgXg9g',
    appId: '1:157073038498:android:bab7165517e7fd67eacbfb',
    messagingSenderId: '157073038498',
    projectId: 'yugioh-card-manager-d3164',
    storageBucket: 'yugioh-card-manager-d3164.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtMQKnt8Yf37KfxPR_ctVB3TtaV1d6Wxk',
    appId: '1:157073038498:ios:0ad1dfacd8b0f084eacbfb',
    messagingSenderId: '157073038498',
    projectId: 'yugioh-card-manager-d3164',
    storageBucket: 'yugioh-card-manager-d3164.firebasestorage.app',
    iosBundleId: 'com.example.yugiohManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtMQKnt8Yf37KfxPR_ctVB3TtaV1d6Wxk',
    appId: '1:157073038498:ios:0ad1dfacd8b0f084eacbfb',
    messagingSenderId: '157073038498',
    projectId: 'yugioh-card-manager-d3164',
    storageBucket: 'yugioh-card-manager-d3164.firebasestorage.app',
    iosBundleId: 'com.example.yugiohManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ686oYbypjumZZHo5vL4Iqp4WxAaBO90',
    appId: '1:157073038498:web:6d38d9ac37c82bd7eacbfb',
    messagingSenderId: '157073038498',
    projectId: 'yugioh-card-manager-d3164',
    authDomain: 'yugioh-card-manager-d3164.firebaseapp.com',
    storageBucket: 'yugioh-card-manager-d3164.firebasestorage.app',
    measurementId: 'G-5W4R06NX63',
  );
}